project:
  type: website

website:
  navbar:
    logo: img/logo_tag.jpg
    logo-alt: logo showing MikeRSpencer.com and human insight for your data needs
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: envelope
        href: mailto:consult@mikerspencer.com
      - icon: linkedin
        href: https://www.linkedin.com/in/mikerspencer/
      - icon: mastodon
        href: https://mastodon.scot/@mikerspencer

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



