project:
  type: website

website:
  title: "mikerspencer.com"
  navbar:
    logo: img/logo_tag.jpg
    logo-alt: logo showing MikeRSpencer.com and human insight for your data needs
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



