project:
  type: website

website:
  site-url: "https://www.quarto.org"
  navbar:
    logo: img/logo_trans_inv.png
    logo-alt: logo showing MikeRSpencer.com and human insight for your data needs
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    tools:
      - icon: envelope
        href: mailto:consult@mikerspencer.com
      - icon: linkedin
        href: https://www.linkedin.com/in/mikerspencer/
      - icon: mastodon
        href: https://mastodon.scot/@mikerspencer

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



