---
title: "About Mike"
---

Mike is a data scientist tackling challenges in economics and sociology research. His work is diverse and includes agriculture, mental health, digital economy and other topics.
Within his research group, he is also responsible for data management and data strategy.

Mike has a PhD from the University of Edinburgh, where he studied snow hydrology.
His research was based around a historic dataset (Snow Survey of Great Britain), which he used to demonstrate a link between snow cover and climate fluctuations and better understand snow cover and melt frequency through computer simulation, machine learning and statistics.
You can read more about Mike's research on his blog, scottishsnow.

Prior to Mike's return to university he worked as a hydrologist for Environment Agency Wales and Halcrow Group Ltd.
Mike worked on projects including river and coastal flood mapping, flood defence scheme design, river re-alignment, flood forecasting (operationally and model development) and flood risk assessment.
Mike graduated from Lancaster University in 2004 with a BSc (hons) in Environmental Science.

Mike is a fellow of the Royal Statistical Society and member of the Society of Research Software Engineers.

Add CV

{{< ai orcid >}}