---
title: "Software and tools"
---

Let me introduce you to the software I use.
All the tools in this list are free at the point of use and available with open source licences.
These are tools and tech I can support you with:

* Programming
   * [R](https://cran.r-project.org/): Statistical and programming software
   * [RStudio](https://posit.co/products/open-source/rstudio): Development environment for R
   * Linux and Bash: for scaling and automation
   * [Git](https://git-scm.com/): Version control software (for use with Github, Bitbucket, Gitlab, Codeberg, etc.)
* Spatial and GIS
   * [GRASS](https://grass.osgeo.org/): Geographic information system
   * [QGIS](https://qgis.org/): Geographic information system
* Data storage
   * [SQLite](https://www.sqlite.org/), [PostgreSQL](https://www.postgresql.org/), [MySQL](https://www.mysql.com/)
   * [Parquet](https://parquet.apache.org/), [Arrow](https://arrow.apache.org/) and [partitioned data](https://hive.apache.org/)
* Other
   * [Scribus](https://www.scribus.net/): Desktop publishing
   * [Logseq](https://logseq.com/): personal knowledge management

My operating system of choice is Fedora, which is built on Linux (like Android is).
A lot of the software on this page is available for Windows and Macs, but it is all available for Linux systems.
I switched from using Windows to Ubuntu in early 2011 and have not regretted the decision.
I have it installed on my home and work desktops and also my laptop, it’s great having all machines running the same operating system with the same software installed.

Some of the software I use falls under the umbrella of OSGeo, which is an organisation that looks after spatial software like GRASS and QGIS.
They maintain an image operating system containing all their spatial projects.
If you want to try some out, this is an excellent place to start.
OSGeo also has country specific chapters; as most of my blog readers are from the UK here is the UK OSGeo chapter.
The local chapters are great for putting you in touch with other users and as a place to ask advice and find assistance.

