project:
  type: website
  output-dir: ../_site/id
  preview:
    port: 4200
    browser: false
  resources:
    - robots.txt
lang: "id"
website:
  title: "Rouze Theme"
  site-url: https://rouze.hervyqa.dev/id
  open-graph:
    locale: id_ID
  image: asset/cover.webp
  twitter-card:
    creator: "@username"
    site: "@username"
  favicon: /asset/favicon.png
  repo-url: https://git.sr.ht/~username/repository
  repo-branch: main
  repo-link-target: _blank
  back-to-top-navigation: false
  page-navigation: true
  search:
    location: navbar
    type: textbox
    keyboard-shortcut: ["/"]
  navbar:
    background: dark
    logo: asset/logo.svg
    logo-alt: "Rouze Theme"
    title: false
    collapse-below: lg
    tools:
      - icon: mastodon
        href: "https://mastodon.social/@username"
        target: "_blank"
        text: Mastodon
      - icon: git
        href: "https://git.sr.ht/~username/repository"
        target: "_blank"
        text: Sourcehut
      - icon: rss-fill
        href: blog/index.xml
        target: "_blank"
        text: Feed RSS
    left:
      - icon: house-fill
        href: index.qmd
        text: Beranda
      - icon: file-earmark-code-fill
        text: Panduan
        menu:
          - icon: journal-code
            text: Mulai
            href: docs/start/index.qmd
          - icon: code-slash
            text: Membangun
            href: docs/build/index.qmd
      - icon: book-fill
        text: Warta
        href: blog/index.qmd
      - icon: briefcase-fill
        text: Projek
        href: project/index.qmd
      - icon: easel-fill
        text: Salindia
        href: slide/index.qmd
      - icon: person-fill
        text: Tentang
        menu:
          - icon: file-person-fill
            text: Penulis
            href: author/index.qmd
          - icon: people-fill
            text: Tentang kami
            href: about/index.qmd
    right:
      - icon: translate
        text: Bahasa
        menu:
          - icon: gear-fill
            text: English
            href: ..
          - icon: gear-fill
            text: French
            href: ../fr
          - icon: gear-fill
            text: Indonesia
            href: ../id
          - icon: gear-fill
            text: Japanese
            href: ../ja
  sidebar:
    - id: "start"
      title: "Start"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Start
          href: docs/start/index.qmd
        - section: "Start"
          contents:
            - docs/start/quarto-1/index.qmd
            - docs/start/quarto-2/index.qmd
        - section: "Deploy"
          contents:
            - docs/deploy/quarto-1/index.qmd
            - docs/deploy/quarto-2/index.qmd
    - id: "build"
      title: "Build"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Build
          href: docs/build/index.qmd
        - section: "Product"
          contents:
            - docs/product/quarto-1/index.qmd
            - docs/product/quarto-2/index.qmd
        - section: "Service"
          contents:
            - docs/service/quarto-1/index.qmd
            - docs/service/quarto-2/index.qmd
  page-footer:
    left: |
      <i class="bi bi-c-circle"></i> 2026 oleh Rouze Theme
      <br><i class="bi bi-envelope-at-fill"></i> Surel: [your.mail@company.org](mailto:your.mail@company.org)
      <br><i class="bi bi-geo-alt-fill"></i> Mojokerto, East Java, Indonesia. 61385
    center:
      - text: Tentang
        href: about/index.qmd
      - text: Ketentuan
        href: terms/index.qmd
      - text: Privasi
        href: privacy/index.qmd
      - text: Licensi
        href: license/index.qmd
    right: |
      Dibangun dengan [R](https://www.r-project.org) & [Quarto](https://quarto.org).
      <br> Dilisensikan dengan [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.id).
      <br> ![cc-by-nc](/asset/by-nc.svg)
bibliography: asset/bib/references.bib
format:
  html:
    theme:
      light:
        - cosmo
        - brand
        - asset/styles/theme.scss
      dark:
        - cosmo
        - brand
        - asset/styles/theme-dark.scss
    css: asset/styles/styles.css
    font:
      mainfont: system-ui
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    mermaid:
      theme: default
      respect-user-color-scheme: true
    from: markdown+emoji
    code-copy: true
    code-overflow: scroll
    smooth-scroll: true
    lightbox: true
    citation-location: document
    citation: true
    citeproc: true
    footnotes-hover: true
    link-external-newwindow: true
    number-sections: true
    reference-location: document
    html-math-method:
      method: mathml
editor: visual
execute:
  freeze: false
